### ISSUE TITLE
Can the aspectRatio only affect the corner stick?

### ISSUE THREAD

**Issue by siskaoffeo** [pinkcao/vue-drag-resize-rotate#1]
Is there a way to only make the aspectRatio affect the corner stick?

Something like this:
https://www.loom.com/share/da58f62d89f94488bc6ea5e57c60d270

**Comment by pinkcao** [comment]
it's not supported now, but I will try to make that possible in this week, maybe add some new props

**Comment by pinkcao** [comment]
it's supported now. add  :aspectRatioSticks="[tl, tr, bl, br]" to just affect the corner sticks,
now you can choose the certain sticks that will be affected by aspectRatio
props aspectRatioSticks will work only when :aspectRatio="true"
try in demo!
also added Grid feature

**Comment by siskaoffeo** [comment]
wow. thank you so much! this looks great!
