### ISSUE TITLE
图片大小变换报错

### ISSUE THREAD

**Issue by julin69** [pinkcao/vue-drag-resize-rotate#2]
![image](https://user-images.githubusercontent.com/34527159/147207022-c798857b-8808-461a-9da6-7f91e6de0590.png)

当设置aspectRatio为true时，拖动左右两边的滑块时报错
![image](https://user-images.githubusercontent.com/34527159/147207253-f0d84520-8c50-478d-8dd3-2fd722ff863d.png)
代码如下所示：
![image](https://user-images.githubusercontent.com/34527159/147207357-8ad57051-1549-45cf-a4e2-be75b5cb82e1.png)
使用的是1.2.3的版本，vue2

**Comment by pinkcao** [comment]
我没复现出来，可以看一下你的resize和rotate方法怎么写的吗
我觉得可能是这两个方法写的有错误
```
    resize(newRect) {
      this.width = newRect.width;
      this.height = newRect.height;
      this.top = newRect.top;
      this.left = newRect.left;
    },
```
```
    rotate(deg) {
      this.deg = deg
    },
```
这样再尝试一下？
