### ISSUE TITLE
黑色的边框

### ISSUE THREAD

**Issue by julin69** [pinkcao/vue-drag-resize-rotate#3]
旋转的时候有时候会出现黑色的边框，重新选中的时候又没有了
![image](https://user-images.githubusercontent.com/34527159/147332328-e266f174-8dba-4ead-af91-b1a203ca17a0.png)

**Comment by julin69** [comment]
正常选中的时候是这样的
![image](https://user-images.githubusercontent.com/34527159/147332392-465dbba0-69b8-45e0-b119-dd0d378b5b28.png)
旋转的时候，在图片上松开鼠标就会出现黑框，在图片外面松开鼠标就不会出现黑框

**Comment by julin69** [comment]
当出现黑框的时候图片下面有间隙
![image](https://user-images.githubusercontent.com/34527159/147333271-4ef0c876-ee53-4248-b853-5ca3db5c82d8.png)

**Comment by pinkcao** [comment]
已修正，可以再试一下
