### ISSUE TITLE
Error when using NPM on a VueJS2 Project :

### ISSUE THREAD

**Issue by matheusvps** [pinkcao/vue-drag-resize-rotate#6]
This is a Vue 2 Project. But a dependency into your npm install for Vue2 version requires Vue3

**Comment by pinkcao** [comment]
Can I have a look at your package.json? seems your dependencies maybe include vue-codemirror? in this project maybe nothing will relate to vue-codemirror

**Comment by matheusvps** [comment]
> Can I have a look at your package.json? seems your dependencies maybe include vue-codemirror? in this project maybe nothing will relate to vue-codemirror

Solved ! You can close it :)
